# Generated by Django 3.0.7 on 2020-07-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagueapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=75)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagueapp.League')),
            ],
        ),
    ]
