# Generated by Django 3.0.7 on 2020-07-21 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagueapp', '0002_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=75)),
                ('location', models.TextField(default=None, max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=75)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagueapp.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagueapp.Team')),
            ],
        ),
    ]
