# Generated by Django 3.0.7 on 2020-07-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueapp', '0003_team_teamseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=75)),
                ('last_name', models.CharField(default=None, max_length=75)),
                ('height', models.FloatField(default=None, help_text='In cm', max_length=25)),
                ('weight', models.FloatField(default=None, max_length=25)),
                ('date_of_birth', models.DateField(default=None, max_length=75)),
            ],
        ),
    ]
