# Generated by Django 3.0.7 on 2020-07-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagueapp', '0005_auto_20200722_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('score', models.CharField(default=None, max_length=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagueapp.TeamSeason')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leagueapp.TeamSeason')),
            ],
        ),
    ]
